.watch-dirs:
  web:
    - apps/web/**/*
  api:
    - apps/api/**/*

build-web:
  extends: .build-client-nextjs
  variables:
    SERVICE_NAME: "web"
    SRC_PATH: ./apps/web
  rules:
    - changes: !reference [".watch-dirs", "web"]

deploy-web:
  extends: .deploy-firebase
  variables:
    SERVICE_NAME: "web"
  needs: ["build-web"]
  rules:
    - if: $CI_COMMIT_TAG =~ /release/
      changes: !reference [".watch-dirs", "web"]
      when: manual
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_REF_SLUG =~ /develop|staging/
      changes: !reference [".watch-dirs", "web"]

build-api:
  extends: .build-service
  variables:
    SERVICE: api
    NPM_WORKSPACE: "demo-api"
    DOCKERFILE: microservice.dockerfile
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/api
  rules:
    - changes: !reference [".watch-dirs", "api"]

deploy-api:
  extends: .deploy-ssh
  variables:
    KIND: "deployment"
    SERVICE_NAME: "api"
    CONTAINER_NAME: "api-container"
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/api
  needs: ["build-api", "publish-api"]
  rules:
    - if: $CI_COMMIT_TAG =~ /release/
      changes: !reference [".watch-dirs", "api"]
      when: manual
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_REF_SLUG =~ /develop|staging/
      changes: !reference [".watch-dirs", "api"]

publish-api:
  extends: .publish-image
  variables:
    SERVICE_NAME: "api"
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/api
  needs: ["build-api"]
  rules:
    - if: $CI_COMMIT_TAG =~ /release/
      changes: !reference [".watch-dirs", "api"]
      when: manual
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_REF_SLUG =~ /develop|staging/
      changes: !reference [".watch-dirs", "api"]
